### ISSUE TITLE
odoo v9 

### ISSUE THREAD

**Issue by jjlopezg** [NorthwoodsSoftware/GoJS#27]
good afternoon, do you know where the error may come:

Uncaught Error: Trying to set undefined property "length" on object: Diagram ""
Uncaught Error: Trying to set undefined property "length" on object: Diagram ""

http://127.0.0.1:8069/web/content/1020-bda5065/web.assets_backend.js:7035
Traceback:
Error: Trying to set undefined property "length" on object: Diagram ""
    at Error (native)
    at Object.k (http://127.0.0.1:8069/web/content/1020-bda5065/web.assets_backend.js:7035:4193)
    at Object.pu (http://127.0.0.1:8069/web/content/1020-bda5065/web.assets_backend.js:7037:1256)
    at hn (http://127.0.0.1:8069/web/content/1020-bda5065/web.assets_backend.js:7194:898)
    at fn (http://127.0.0.1:8069/web/content/1020-bda5065/web.assets_backend.js:7191:259)
    at OdooClass.render_map (http://127.0.0.1:8069/web/content/1020-bda5065/web.assets_backend.js:7371:168)
    at OdooClass.<anonymous> (http://127.0.0.1:8069/web/content/1020-bda5065/web.assets_backend.js:7371:420)
    at OdooClass.trigger (http://127.0.0.1:8069/web/content/246-1aefcb8/web.assets_common.js:2613:180)
    at OdooClass.trigger (http://127.0.0.1:8069/web/content/246-1aefcb8/web.assets_common.js:2615:669)
    at _notify (http://127.0.0.1:8069/web/content/1020-bda5065/web.assets_backend.js:3256:443)

**Comment by simonsarris** [comment]
No, except that `length` is not a property of `Diagram`, as the error states.

This is not an appropriate use of the Issues.
