### ISSUE TITLE
When loading images too much

### ISSUE THREAD

**Issue by gaoconggit** [NorthwoodsSoftware/GoJS#41]
Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at Xl.bk (http://localhost:60074/_theme/go/go.js:106:2083)
    at Xl.f.bf (http://localhost:60074/_theme/go/go.js:80:257)
    at z.f.bk (http://localhost:60074/_theme/go/go.js:88:1354)
    at z.f.bf (http://localhost:60074/_theme/go/go.js:80:257)
    at S.f.bk (http://localhost:60074/_theme/go/go.js:88:1354)
    at S.f.bf (http://localhost:60074/_theme/go/go.js:80:257)
    at De.f.bf (http://localhost:60074/_theme/go/go.js:55:4954)
    at c (http://localhost:60074/_theme/go/go.js:61:1872)
    at C.bf (http://localhost:60074/_theme/go/go.js:61:1920)
    at Jg (http://localhost:60074/_theme/go/go.js:60:4292)

**Comment by WalterNorthwoods** [comment]
Thanks for the error message and stack, but what version of go.js is it?
Could you tell us how to reproduce the error?

**Comment by WalterNorthwoods** [comment]
(Closed due to lack of information.)

**Comment by gaoconggit** [comment]
I'm sorry to see this answer now.


$(go.Picture,
            {
                name: 'Picture',
                maxSize: new go.Size(80, 100)
               //,desiredSize: new go.Size(80, 100)  //When using desiredSize, if the image 404, go.js will die
                , margin: new go.Margin(3, 3, 3, 3)
            }
When using desiredSize, if the image 404, go.js will die,Use maxSize to solve this problem

**Comment by simonsarris** [comment]
For general support, please use the [contact form](http://www.nwoods.com/contact.html) or the [support forum](https://forum.nwoods.com/c/gojs).

If this is a bug and you can reproduce a case, say in [codepen](http://codepen.io/simonsarris/pen/ORwoLA?editors=1010), we'll investigate it.
